<tr class="setting-verificationlist" id="VerificationID_<?php echo $wo['verification']['id']?>" >
   <td><?php echo $wo['verification']['id']?> </td>
   <td>
      <a href="../@<?php echo $wo['verification']['request_from']['username']; ?>" target="_blank">
      <img src="<?php echo GetMedia( $wo['verification']['request_from']['avater'])?>" class="setting-avatar" alt="<?php echo $wo['verification']['request_from']['name']; ?> Profile Picture">
      <?php
      echo $wo['verification']['request_from']['username'] . '(' . $wo['verification']['request_from']['first_name'] . ' ' . $wo['verification']['request_from']['last_name']; ?>
      </a>

         <span class="pointer toggle-verification-request" onclick="Wo_ToggleVerfRequest(<?php echo $wo['verification']['id']; ?>,this)">
            <i class="fa fa-caret-down" aria-hidden="true"></i>
         </span>

   </td>
   <td>
      <span class="verify pointer" onclick="Wo_Verify(<?php echo $wo['verification']['request_from']['id']?>,<?php echo $wo['verification']['id']?>,'');">
      <i class="fa fa-check-circle progress-icon" data-icon="check-circle"></i> Verify
      </span>|
      <span class="delete-verification pointer" onclick="Wo_DeleteVerification(<?php echo $wo['verification']['id']?>);">
      <i class="fa fa-trash-o progress-icon" data-icon="trash-o"></i> Ignore
      </span>
   </td>
</tr>

   <tr id="review-verif-request-info-<?php echo $wo['verification']['id']; ?>" style="display: none;">
      <td colspan="4">
         <div class="review-verif-request-cont">
            <div class="verification-request-img-<?php echo $wo['verification']['id']; ?>">
               <a 
               href="<?php echo GetMedia($wo['verification']['passport']); ?>"
               style="
               background-image: url('<?php echo GetMedia($wo['verification']['passport']); ?>');
               width: 100%; 
               height: 150px; 
               display: block;
               background-size: cover;
               "
               > 
               </a>
               <a href="<?php echo GetMedia($wo['verification']['passport']); ?>"></a>
            </div>
             <div class="verification-request-img-<?php echo $wo['verification']['id']; ?>">
               <a 
               href="<?php echo GetMedia($wo['verification']['photo']); ?>"
               style="
               background-image: url('<?php echo GetMedia($wo['verification']['photo']); ?>');
               width: 100%; 
               height: 150px; 
               display: block;
               background-size: cover;
               "
               > 
               </a>
               <a href="<?php echo GetMedia($wo['verification']['photo']); ?>"></a>
            </div>
            <h4><?php echo $wo['verification']['user_name']; ?></h4>
            <p><?php echo $wo['verification']['message']; ?></p>
         </div>
      </td>
   </tr>