<tr class="setting-userlist" id="UserID_<?php echo $wo['userlist']['id']?>" data-user-id="<?php echo $wo['userlist']['id']?>">
   <td><?php echo $wo['userlist']['id']?></td>
   <td>
      <a href="<?php echo $wo['config']['site_url'] . '/@'.$wo['userlist']['username']; ?>">
      <img src="<?php echo GetMedia($wo['userlist']['avater']); ?>" class="setting-avatar" >
      <?php echo $wo['userlist']['username']; ?>
      </a>
   </td>
   <td><?php echo $wo['userlist']['src']?></td>
   <td><?php echo $wo['userlist']['email']?></td>
   <td><?php echo $wo['userlist']['ip_address']?></td>
   <td><?php echo (Wo_UserActive($wo['userlist']['username']) === true) ? '<span class="label label-success">' . __('active') . '</span>': '<span class="label label-danger">' . __('pending') . '</span>';?></td>
</tr>