<div class="container-fluid">
    <div class="block-header">
        <h2>Updates > Updates & Bug Fixes</h2>
    </div>
    <!-- Vertical Layout -->
    <div class="row">
         <div class="col-lg-6 col-md-6">
            <div class="card updates-layout ">
                <div class="header">
                    <h2>New update is available!</h2>
                </div>
                <div class="body">
                    <div>The following version(s) will be installed:</div>
                    <div class="updates"></div>
                    <button class="btn btn-success waves-effect waves-light m-t-10 run-update" onclick="Wo_RunUpdates()">Install Updates</button>
                    <button class="btn btn-success waves-effect waves-light m-t-10 download-update" onclick="Wo_DownloadUpdates()">Download Updates</button>
                    <br><br>
                    <div>
                    	1. "Install updates" button will download and automatically update your site to latest version(s). <span class="help-block red" style="color: red">Note: "Install updates" will repalce and overwrite all your code modifications, If you want to keep your modifications, please use the manual process (download button).<br>Make sure to create a backup before starting the update process.</span><br>
                    </div>
                     <div>
                    	2. "Download updates" button will download the latest version(s) and save them to your server disk, you can find them in "/updates" folder. You can update your site manually using the guide included in the update.
                    </div>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <!-- #END# Vertical Layout -->
<script>

function Wo_CheckForUpdates() {
	var purchase_code = $('.purchase_code').val();
	var script_version = $('#script-version').val();
	$('.check-update-button').text('Please wait..');
	$.get(Wo_Ajax_Requests_File(), {f: 'check_for_updates', purchase_code: purchase_code}, function (data) {
		if (data.status == 200) {
			$('.updates-layout').removeClass('hidden');
			$('.updates').html('<ul class="list-group"></ul>').find('ul').append('<li class="list-group-item hidden">Versions</li>');;
			data.versions.forEach(function(entry) {
			    $('.updates').find('ul').append('<li class="list-group-item"> ' + entry + '</li>');
			});
			$('#script-version').val(data.script_version);
		} else if (data.status == 300) {
			alert('Your site is up to date.');
		} else if (data.status == 400) {
			alert(data.ERROR_NAME);
		}  else  {
			alert('Error while connecting to server, please check your details');
		}
		$('.check-update-button').text('Check For Updates');
	});
}
function Wo_DownloadUpdates() {
	$('.download-update').text('Downloading, Please wait..');
	var purchase_code = $('.purchase_code').val();
	$.get(Wo_Ajax_Requests_File(), {f: 'download_updates', purchase_code: purchase_code}, function (data) {
		if (data.status == 200) {
			alert('The update(s) was downloaded.');
			$('.updates-layout').addClass('hidden');
		} else if (data.status == 300) {
			alert('Your site is up to date.');
		} else if (data.status == 400) {
			alert(data.ERROR_NAME);
		}  else  {
			alert('Error while connecting to server, please check your details');
		}
		$('.download-update').text('Download Updates');
	});
}

function Wo_RunUpdates() {
	$('.run-update').text('Updating, Please wait..');
	var purchase_code = $('.purchase_code').val();
	var script_version = $('#script-version').val();
	$.get('<?php echo $wo['config']['site_url']?>/updater.php', {f: 'run_updater', purchase_code: purchase_code, script_version:script_version}, function (data) {
		if (data.status == 200) {
			alert('Your site was updated, please refresh your page and clean your browser cache.');
			$('.updates-layout').addClass('hidden');
		} else if (data.status == 300) {
			alert('Your site is up to date.');
		} else if (data.status == 400) {
			alert(data.ERROR_NAME);
		}  else  {
			alert('Error while connecting to server, please check your details');
		}
		$('.run-update').text('Install Updates');
	});
}
</script>