<div class="container-fluid">
            <!-- Changelogs -->
            <div class="block-header">
                <h2>CHANGELOGS <small>Updates are provided freely for life-time if you own a valid purchase code.
            </div>
             <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>v1.4.1</h2>
                        </div>
                        <div class="body">
                            <li>[Added] gifts page, you can view the gifts you received from other users.</li>
                            <li>[Added] ability to add, edit, remove countries from the admin panel.</li>
                            <li>[Added] ability to pay admin to unlock private photos (enable/disable).</li>
                            <li>[Added] only pro users could upload videos and pay to unlock.  (enable/disable)</li>
                            <li>[Added] credit system with daily login, earn credits by logining in in daily. </li>
                            <li>[Added] ability to submit verification docs on "start up page" on sign up  (enable/disable) </li>
                            <li>[Added] allow sign up from specific domain only for example gmail.com. </li>
                            <li>[Added] ability to block certain domain sign up like yahoo.com for example.</li>
                            <li>[Fixed] 40+ reported bugs.</li>
                            <li>[Improved] stability & speed. </li>
                        </div>
                    </div>
                </div>
            </div>
             <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>v1.4</h2>
                        </div>
                        <div class="body">
                            <li>[Added] ability to upload videos + FFMPEG.</li>
                            <li>[Added] moderator user (admin could set what pages a specific moderator could access in the admin).</li>
                            <li>[Added] ability to lock gender after someone selects during sign up.</li>
                            <li>[Added] friend system, user can add friends / accept decline (enable / disable.)</li>
                            <li>[Added] blacklist system, block user by email, username and IP. </li>
                            <li>[Added] affiliate system, users can earn money by refrerring users. </li>
                            <li>[Added] users on home page (enable/disable). </li>
                            <li>[Added] ability to send mock emails to user who didn't login for week/month/year/ from admin panel.</li>
                            <li>[Added] ability to limit number of max photo a user can upload from admin panel (unlimited for pro user)</li>
                            <li>[Added] ability to review photos and videos by admin with (enable/disable)</li>
                            <li>[Fixed] 20+ reported bugs.</li>
                            <li>[Improved] stability & speed. </li>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>v1.3.2</h2>
                        </div>
                        <div class="body">
                            <li>[Fixed] API issues.</li>
                            <li>[Fixed] 10+ reported bugs.</li>
                            <li>[Improved] stability & speed. </li>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>v1.3.1</h2>
                        </div>
                        <div class="body">
                            <li>[Fixed] API issues.</li>
                            <li>[Fixed] 10+ reported bugs.</li>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>v1.3</h2>
                        </div>
                        <div class="body">
                            <li>[Added] the ability to make the site fully free for a spasefic gender.</li>
                            <li>[Added] the ability to make site completely free.</li>
                            <li>[Added] success stories system.</li>
                            <li>[Added] blog system (only admin can create blogs). </li>
                            <li>[Added] hot or not system. </li>
                            <li>[Added] image webcam verification system.</li>
                            <li>[Added] spam warning, user won't be able to send messages for 24 hours if they were marked as spam.</li>
                            <li>[Added] one signal support. </li>
                            <li>[Fixed] few reported bugs.</li>
                            <li>[Improved] SQL indexes + speed.</li>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>v1.2.2</h2>
                        </div>
                        <div class="body">
                            <li>[Fixed] API issues.</li>
                            <li>[Fixed] few reported bugs.</li>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>v1.2.1</h2>
                        </div>
                        <div class="body">
                            <li>[Added] request limits for user activations in admin panel > general settings. </li>
                            <li>[Fixed] few reported bugs.</li>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>v1.2</h2>
                        </div>
                        <div class="body">
                            <li>[Added] email notifications.</li>
                            <li>[Added] the ability to see suggestion of users living in the same country or state if there is no user from same country then other should appear. </li>
                            <li>[Added] the ability to enable disable pro system. </li>
                            <li>[Added] the ability to randomize pro users section at the moment it shows latest.</li>
                            <li>[Added] the ability to create custom pages. </li>
                            <li>[Added] the ability for users to upload private pictures, and once the user matched with them, they can see their pictures. </li>
                            <li>[Added] video / audio calls API.</li>
                            <li>[Added] the ability to create custom fields for search and profile. </li>
                            <li>[Added] the ability to turn off or on audio/video calls for pro users only or all users.</li>
                            <li>[Improved] search system.</li>
                            <li>[Improved] MySQL queries.</li>
                            <li>[Improved] site speed.</li>
                            <li>[Fixed] few reported bugs.</li>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>v1.1.2</h2>
                        </div>
                        <div class="body">
                            <li>[Added] ads slots, now admin can add ads on 4 slots on the site.</li>
                            <li>[Improved] site speed.</li>
                            <li>[Fixed] few reported bugs.</li>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>v1.1</h2>
                        </div>
                        <div class="body">
                            <li>[Added] video and audio calls.</li>
                            <li>[Added] fake user generator. </li> 
                            <li>[Added] announcement system.</li>
                            <li>[Added] messaging approval / decline system, user can decline a message from other users.</li>
                            <li>[Added] user now can see himself in pro sidebar if he boosted.</li>
                            <li>[Added] daily like limit, user can't like more than X users per day. </li>
                            <li>[Added] bank payments system, user can pay via bank local payments.</li>
                            <li>[Added] the ability to manage genders from admin panel.</li>
                            <li>[Added] cookie law bar.</li>
                            <li>[Added] the ability for pro user to change his country, and relocate.</li>
                            <li>[Added] SMS gateaway payment using: paysera.com</li>
                            <li>[Added] the ability to switch between Miles and KM.</li>
                            <li>[Added] Maintenance mode.</li>
                            <li>[Added] Night mode.</li>
                            <li>[Added] support for RTL languges.</li>
                            <li>[Removed] landing page, user land on login page now.</li>
                            <li>[Improved] site speed.</li>
                            <li>[Fixed] few reported bugs.</li>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>v1.0</h2>
                        </div>
                        <div class="body">
                            Version 1.0 released on 2019.
                        </div>
                    </div>
                </div>
            </div>
        </div>