<div class="container-fluid">
    <div class="block-header">
        <h2>Pages > Manage success stories</h2>
    </div>
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="header">
                    <h2>Manage & Edit success stories</h2>
                </div>
                <div class="body">
                    <div class="table-responsive1">
                        <table class="table table-bordered table-striped table-hover">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>User</th>
                                <th>With User</th>
                                <th>Quote</th>
                                <th>Content</th>
                                <th>Start Story Date</th>
<!--                                <th>Publish Date</th>-->
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach (Wo_GetSuccessStories() as $wo['page']) { ?>
                                <tr class="setting-postlist" id="<?php echo $wo['page']['id'];?>">
                                    <td width="5%"><?php echo $wo['page']['id'];?></td>
                                    <td width="10%">
                                        <?php $udata = userData($wo['page']['user_id']);?>
                                        <a href="<?php echo $wo['site_url'] . '/@' . $udata->username ; ?>" target="_blank" >
                                            <img src="<?php echo $udata->avater->avater; ?>" class="setting-avatar" alt="<?php echo $udata->full_name?> Profile Picture">
                                            <?php echo $udata->full_name;?>
                                        </a>
                                    </td>
                                    <td width="10%">
                                        <?php $udata2 = userData($wo['page']['story_user_id']);?>
                                        <a href="<?php echo $wo['site_url'] . '/@' . $udata2->username ; ?>" target="_blank" >
                                            <img src="<?php echo $udata2->avater->avater; ?>" class="setting-avatar" alt="<?php echo $udata2->full_name?> Profile Picture">
                                            <?php echo $udata2->full_name;?>
                                        </a>
                                    </td>
                                    <td width="15%"><?php echo $wo['page']['quote'];?></td>
                                    <td width="30%"><?php echo br2nl(html_entity_decode( substr($wo['page']['description'], 0, 150) )) ;?>...</td>
                                    <td width="10%"><?php echo $wo['page']['story_date'];?></td>
<!--                                    <td width="10%">-->
<!--                                        <span style="color:#607D8B;font-size: 11px;font-weight: bold;" class=" ajax-time" title="--><?php //echo date('c', $wo['page']['created_at']); ?><!--">-->
<!--                                            --><?php //echo Time_Elapsed_String($wo['page']['created_at']);?>
<!--                                        </span>-->
<!--                                    </td>-->
                                    <td width="20%">
                                        <a class="btn btn-info waves-effect waves-light" href="<?php echo Wo_LoadAdminLinkSettings('edit-success-stories?id=' . $wo['page']['id']); ?>">EDIT</a>
                                        <button class="btn btn-danger waves-effect waves-light" onclick="Wo_DeleteSuccessStory(<?php echo $wo['page']['id'];?>);">DELETE</button>
                                        <?php if( $wo['page']['status'] === "0" ){ ?>
                                            <button class="btn btn-warning waves-effect waves-light" onclick="Wo_ApproveSuccessStory(<?php echo $wo['page']['id'];?>);">Approve</button>
                                        <?php }else{ ?>
                                            <button class="btn  waves-effect waves-light" onclick="Wo_DisApproveSuccessStory(<?php echo $wo['page']['id'];?>);">Disapprove</button>
                                        <?php }?>
                                    </td>
                                </tr>
                            <?php } ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>
<!-- #END# Vertical Layout -->
<script>
    $(function () {
        $('table').DataTable();
    });
    function Wo_DeleteSuccessStory(id) {
        if (id == '') {
            return false;
        }
        if (!confirm('Are you sure you want to delete this Success story?')) {
            return false;
        }
        var hash_id = '<?php echo Wo_CreateSession();?>';
        $('#' + id).fadeOut(300, function () {
            $(this).remove();
        });
        $.get(Wo_Ajax_Requests_File(), {f: 'admin_setting', s:'delete_success_stories', p: 'manage-success-stories', id:id, hash_id: hash_id});
    }
    function Wo_ApproveSuccessStory(id) {
        if (id == '') {
            return false;
        }
        var hash_id = '<?php echo Wo_CreateSession();?>';
        $.get(Wo_Ajax_Requests_File(), {f: 'admin_setting', s:'approve_success_stories', p: 'manage-success-stories', id:id, hash_id: hash_id}
            , function(data, status){
                location.reload();
            });
    }
    function Wo_DisApproveSuccessStory(id) {
        if (id == '') {
            return false;
        }
        var hash_id = '<?php echo Wo_CreateSession();?>';
        $.get(Wo_Ajax_Requests_File(), {f: 'admin_setting', s:'disapprove_success_stories', p: 'manage-success-stories', id:id, hash_id: hash_id}
            , function(data, status){
                location.reload();
            });
    }
</script>