<div class="alert alert-danger announcement-<?php echo $wo['inactiveAnnouncement']['id'];?>">
   <span class="close announcements-option" data-toggle="tooltip" onclick="Wo_DeleteAnnouncement(<?php echo $wo['inactiveAnnouncement']['id'];?>);" title="<?php echo __('delete'); ?>">
   <i class="fa fa-trash"></i>
   </span>
   <span class="close announcements-option" data-toggle="tooltip" onclick="Wo_ActivateAnnouncement(<?php echo $wo['inactiveAnnouncement']['id'];?>);" title="<?php echo __('enable'); ?>">
   <i class="fa fa-check"></i>
   </span>
   <?php echo $wo['inactiveAnnouncement']['text'];?>
   <span class="time ajax-time" title="<?php echo date('c',$wo['inactiveAnnouncement']['time']); ?>">
   <?php echo get_time_ago($wo['inactiveAnnouncement']['time']);?>
   </span>
   <span class="time">
    <?php echo __('views') . ' ' . Wo_GetAnnouncementViews($wo['inactiveAnnouncement']['id']);?>
   </span>
</div>