<?php
$page           = (!empty($_GET['page-id']) && is_numeric($_GET['page-id'])) ? Secure($_GET['page-id']) : 1;
$db->pageLimit  = 20;
$mediafiles = $db->objectbuilder()->orderBy('id', 'DESC')->paginate('mediafiles', $page);

if (($page > $db->totalPages) && !empty($_GET['page-id'])) {
    header("Location: " . Wo_LoadAdminLinkSettings('manage-photos'));
    exit();
}

?>
<div class="container-fluid">
    <div class="block-header">
        <h2>Photos > Manage Photos & Videos</h2>
    </div>
    <!-- Vertical Layout -->
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="header">
                    <h2>Manage Photos & Videos</h2>
                    <?php if ($wo['config']['review_media_files'] == 1) {?>
                        <button onclick="Wo_DisApproveAllPhoto();" type="button" class="btn btn-warning waves-effect waves-light" style="display: inline-block;float: right;margin-top: -23px;margin-left: 13px;">DISAPPROVE ALL</button>
                        &nbsp;
                        <button onclick="Wo_ApproveAllPhoto();" type="button" class="btn btn-success waves-effect waves-light" style="display: inline-block;float: right;margin-top: -23px;">APPROVE ALL</button>
                    <?php } ?>
                </div>
                <div class="clearfix"></div>
                <div class="table-responsive1">
                    <table class="table table-bordered table-striped table-hover">
                        <tbody>
                        <?php
                        foreach ($mediafiles as $mediafilelist) {
                            $wo['mediafilelist'] = $mediafilelist;
                            $wo['mediafilelist']->user = new stdClass();// userData($mediafilelist->user_id,array('username','avater'));
                            $user = $db->where('id', $mediafilelist->user_id)->getOne('users',array('username','avater'));
                            $wo['mediafilelist']->user->username = $user['username'];
                            $wo['mediafilelist']->user->avater->avater = GetMedia($user['avater']);
                            echo Wo_LoadAdminPage('manage-photos/list');
                        }
                        ?>
                        </tbody>
                    </table>
                </div>
                <div class="wo-admincp-feturepager" style="width: 98%;margin: 0 auto;">
                    <div class="pull-left">
                        <span>
                          <?php echo "Showing $page out of " . $db->totalPages; ?>
                        </span>
                    </div>
                    <div class="pull-right">
                        <nav>
                            <ul class="pagination">
                                <li>
                                    <a href="<?php echo Wo_LoadAdminLinkSettings('manage-photos?page-id=1'); ?>" class="waves-effect" title='First Page'>
                                        <i class="material-icons">first_page</i>
                                    </a>
                                </li>
                                <?php if ($page > 1) {  ?>
                                    <li>
                                        <a href="<?php echo Wo_LoadAdminLinkSettings('manage-photos?page-id=' . ($page - 1)); ?>" class="waves-effect" title='Previous Page'>
                                            <i class="material-icons">chevron_left</i>
                                        </a>
                                    </li>
                                <?php  } ?>

                                <?php
                                $nums       = 0;
                                $nums_pages = ($page > 4) ? ($page - 4) : $page;

                                for ($i=$nums_pages; $i <= $db->totalPages; $i++) {
                                    if ($nums < 20) {
                                        ?>
                                        <li class="<?php echo ($page == $i) ? 'active' : ''; ?>">
                                            <a href="<?php echo Wo_LoadAdminLinkSettings('manage-photos?page-id=' . ($i)); ?>" class="waves-effect">
                                                <?php echo $i ?>
                                            </a>
                                        </li>

                                    <?php } $nums++; }?>

                                <?php if ($db->totalPages > $page) { ?>
                                    <li>
                                        <a href="<?php echo Wo_LoadAdminLinkSettings('manage-photos?page-id=' . ($page + 1)); ?>" class="waves-effect" title="Next Page">
                                            <i class="material-icons">chevron_right</i>
                                        </a>
                                    </li>
                                <?php } ?>
                                <li>
                                    <a href="<?php echo Wo_LoadAdminLinkSettings('manage-photos?page-id=' . ($db->totalPages)); ?>" class="waves-effect" title='Last Page'>
                                        <i class="material-icons">last_page</i>
                                    </a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
</div>
</div>



<script>

    function Wo_DeletePhoto(photo_id,photo_file) {
        if (confirm("Are you sure you want to delete this photo?") == false) {
            return false;
        }
        hash_id = '<?php echo Wo_CreateSession();?>';
        $('#PhotoID_' + photo_id).fadeOut(300, function() {
            $(this).remove();
        });
        $.get(Wo_Ajax_Requests_File(),{f:'admin_setting', s:'delete_photo', p: 'manage-photos', photo_id: photo_id, photo_file: photo_file, hash_id: hash_id});
    }

    function Wo_ApprovePhoto(photo_id,photo_file) {
        hash_id = '<?php echo Wo_CreateSession();?>';
        $('#mediafile_' + photo_id).fadeOut(300, function() {
            $(this).remove();
        });
        $.get(Wo_Ajax_Requests_File(),{f:'admin_setting', s:'approve_photo', p: 'manage-photos', photo_id: photo_id, photo_file: photo_file, hash_id: hash_id}, function (data) {
            if(data.status == 200){
                window.location.reload();
            }
        });
    }

    function Wo_DisApprovePhoto(photo_id,photo_file) {
        hash_id = '<?php echo Wo_CreateSession();?>';
        $('#mediafile_' + photo_id).fadeOut(300, function() {
            $(this).remove();
        });
        $.get(Wo_Ajax_Requests_File(),{f:'admin_setting', s:'disapprove_photo', p: 'manage-photos', photo_id: photo_id, photo_file: photo_file, hash_id: hash_id}, function (data) {
            if(data.status == 200){
                window.location.reload();
            }
        });
    }


    function Wo_ApproveAllPhoto() {
        if (confirm("Are you sure you want to Approve all media files?") == false) {
            return false;
        }
        hash_id = '<?php echo Wo_CreateSession();?>';
        $.get(Wo_Ajax_Requests_File(),{f:'admin_setting', s:'approve_all_photo', p: 'manage-photos', hash_id: hash_id}, function (data) {
            if(data.status == 200){
                window.location.reload();
            }
        });
    }

    function Wo_DisApproveAllPhoto() {
        if (confirm("Are you sure you want to DisApprove all media files?") == false) {
            return false;
        }
        hash_id = '<?php echo Wo_CreateSession();?>';
        $.get(Wo_Ajax_Requests_File(),{f:'admin_setting', s:'disapprove_all_photo', p: 'manage-photos', hash_id: hash_id}, function (data) {
            if(data.status == 200){
                window.location.reload();
            }
        });
    }




</script>